-- Phase 2, Step 2: Oracle AI Vector Search — docs table + VECTOR column
--
-- Run as NLQUERYUSER in SQL Developer Web.
-- Populate the table afterwards by running: uv run scripts/embed_docs.py
--
-- Cohere embed-multilingual-v3.0 produces 1024-dimensional float32 vectors.

-- ============================================================
-- STEP 1 — Create the chunks table
-- ============================================================

CREATE TABLE docs_chunks (
    chunk_id   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    doc_name   VARCHAR2(200)        NOT NULL,  -- filename, e.g. 'business_glossary.md'
    chunk_text CLOB                 NOT NULL,  -- raw text of this chunk
    embedding  VECTOR(1024, FLOAT32)           -- Cohere embed-multilingual-v3.0 output
);

-- ============================================================
-- STEP 2 — Vector index (HNSW, cosine similarity)
-- Create AFTER the table is populated with embedded rows.
-- ============================================================

-- Run this after embed_docs.py has inserted all rows:
CREATE VECTOR INDEX docs_chunks_emb_idx
ON docs_chunks (embedding)
ORGANIZATION INMEMORY NEIGHBOR GRAPH
DISTANCE COSINE
WITH TARGET ACCURACY 95;

-- ============================================================
-- STEP 3 — Verify (run after embed_docs.py completes)
-- ============================================================

-- Row count should equal the number of chunks generated by embed_docs.py
SELECT COUNT(*) AS total_chunks FROM docs_chunks;

-- Inspect a sample
SELECT chunk_id, doc_name,
       DBMS_LOB.SUBSTR(chunk_text, 120, 1) AS snippet,
       VECTOR_DIMS(embedding)              AS dims,
       VECTOR_NORM(embedding)              AS norm
FROM docs_chunks
ORDER BY chunk_id;

-- ============================================================
-- STEP 4 — Functional smoke test (run from SQL Developer Web)
--
-- The Python backend performs this query at runtime using a
-- real question embedding. The SQL below is for manual verification
-- only — paste an actual float array for the TO_VECTOR literal.
--
-- Example: replace [...] with an array copied from embed_docs.py output,
-- then run to confirm ranking returns the expected chunk.
-- ============================================================

-- SELECT chunk_id, doc_name,
--        DBMS_LOB.SUBSTR(chunk_text, 200, 1) AS snippet,
--        VECTOR_DISTANCE(embedding,
--            TO_VECTOR('[0.001, 0.002, ...]'),
--            COSINE) AS distance
-- FROM docs_chunks
-- ORDER BY distance ASC
-- FETCH FIRST 3 ROWS ONLY;
